### PR TITLE
Ability to configure the config handle

### LINKED ISSUE #14: Allow using a different config file name from package name
As we discussed at FlatCamp it seems the best option is to add another parameter and update the navigation to use a new `handle` parameter that is then used by Forma to find the file.

### PR DESCRIPTION
**Pull request by edalzell**
Closes #14

### CODE REVIEW

**Comment by afonic** [comment]
Hi @edalzell, will this be merged? It would greatly simplify stuff. :)

**Comment by edalzell** [comment]
> Hi @edalzell, will this be merged? It would greatly simplify stuff. :)

I can look, it's been a while lol.

**Comment by afonic** [comment]
👀

**Comment by edalzell** [comment]
> 👀

Sorry, been dealing with stuff and super busy. I'll get there.

**Comment by afonic** [comment]
No worries, I just saw you merged back main and I thought you forgot to merge the PR.

**Comment by edalzell** [comment]
> No worries, I just saw you merged back main and I thought you forgot to merge the PR.

@afonic Can you give this a try and let me know, I think this should be good to go

**Comment by afonic** [comment]
@edalzell just tried this PR in Resrv, it works just fine, thanks!

**Pull request merged**
